SELECT DISTINCT #בלי כפל
    P.NAME AS professor_name, 
    C.NAME AS course_name
FROM PROFESSOR P
JOIN SCHEDULE S ON P.ID = S.PROFESSOR_ID
JOIN COURSE C ON S.COURSE_ID = C.ID
WHERE P.DEPARTMENT_ID <> C.DEPARTMENT_ID;