SELECT CUSTOMER_ID, COUNT(ID) AS orders_count
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY COUNT(ID) DESC
LIMIT 1; #TOP 1


ORDER BY CASE 
    WHEN STATUS = 'PLACED' THEN 1
    WHEN STATUS = 'IN TRANSIT' THEN 2
    WHEN STATUS = 'DELIVERED' THEN 3
END;